- hosts: snmp_machine
  vars:
    user: ubuntu
    dir: /home/ubuntu
  tasks:
  - name: Run automatic_setup.sh
    shell: |
      sudo apt -y install docker.io
      cd ~/splunk-connect-for-snmp

      echo $(green "Building Docker image")

      sudo docker build -t snmp-local .

      sudo docker save snmp-local > myimage.tar
      sudo microk8s ctr image import myimage.tar

      sudo docker pull splunk/splunk:latest
      echo $(green "Running Splunk in Docker")
      sudo docker run -d -p 8000:8000 -p 8088:8088 -p 8089:8089 -e SPLUNK_START_ARGS='--accept-license' -e SPLUNK_PASSWORD='changeme2' splunk/splunk:latest
    args:
      chdir: "{{ dir }}/splunk-connect-for-snmp/integration_tests/"

  - name: Run mikrok8s command
    become: yes
    command: microk8s helm3 install snmp -f values.yaml /home/ubuntu/splunk-connect-for-snmp/charts/splunk-connect-for-snmp --namespace=sc4snmp --create-namespace &
    args:
      chdir: "{{ dir }}/splunk-connect-for-snmp/integration_tests/"