- hosts: bitops_servers
  vars:
    user: ubuntu
    dir: /home/ubuntu
  tasks:
  - name: Change the working directory to somedir/ before executing the command.
    command: ./automatic_setup.sh
    args:
      chdir: "{{ dir }}/splunk-connect-for-snmp/integration_tests/"

  - name: mikrok8s
    become: yes
    command: microk8s helm3 install snmp -f values.yaml ~/splunk-connect-for-snmp/charts/splunk-connect-for-snmp --namespace=sc4snmp --create-namespace
    args:
      chdir: "{{ dir }}/splunk-connect-for-snmp/integration_tests/"