name: integration-tests
on:
  push:
    branches:
      - "test/adding-integration-tests"


jobs:
  run-integration-tests:
    name: run tests
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[run-it]')"
    steps:
      - uses: actions/checkout@v2
      - name: Archieve repository
        working-directory: /home/runner/work/splunk-connect-for-snmp
        run: tar -czf splunk-connect-for-snmp.tgz splunk-connect-for-snmp
      - name: debug
        run: timeout 1m cp /home/runner/work/splunk-connect-for-snmp/splunk-connect-for-snmp.tgz $GITHUB_WORKSPACE/integration_tests/scripts
      - uses: hashicorp/setup-terraform@v1
      - name: Install ansible
        run: sudo apt-get install ansible
      - name: Set AWS varaibles in terraform file
        working-directory: ./integration_tests/scripts
        run: envsubst < main.tf.tmpl > main.tf
        env:
          AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
          AWS_SUBNET: ${{ secrets.AWS_SUBNET }}

      - name: Create AWS test environment
        run: terraform init && terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./integration_tests/scripts

      - name: Setup Integration tests
        run: sleep 30 && timeout 25m ansible-playbook -vvvv playbook.yml || true
        working-directory: ./integration_tests/scripts
      - run: ls -la /tmp

      - name: Run Integration tests
        run: timeout 10m ansible-playbook -vvvv run-tests.yml
        working-directory: ./integration_tests/scripts

#      - name: Run Integration tests
#        run: ansible-playbook -v run-tests.yml
#        working-directory: ./integration_tests/scripts

      - name: Destroy AWS test environment
        if: always()
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./integration_tests/scripts
